#include "observe.hpp"
#include <cstdio>
#include <cstddef>
using namespace iq4::f1::display06;
namespace geometry03=iq4::f1::geometry03;
#define BEGIN(T) std::printf("\"" #T "\":{\"bytes\":%zu,\"fields\":{",sizeof(T));bool first=true;
#define FIELD(T,M) std::printf("%s\"" #M "\":{\"offset\":%zu,\"bytes\":%zu}",first?"":",",offsetof(T,M),sizeof(((T*)nullptr)->M));first=false;
#define END() std::printf("}}");
int main(){std::printf("{");
 {BEGIN(Published) FIELD(Published,sequence) FIELD(Published,bytes) FIELD(Published,schema) FIELD(Published,reserved) FIELD(Published,metadata) END()}
 std::printf(",");{BEGIN(Metadata) FIELD(Metadata,schema) FIELD(Metadata,bytes) FIELD(Metadata,result) FIELD(Metadata,kind) FIELD(Metadata,exact_user_sha256) FIELD(Metadata,exact_user_bytes) FIELD(Metadata,boundary_attempts) FIELD(Metadata,paint_attempts) FIELD(Metadata,publication_epoch) FIELD(Metadata,source_dispatch_epoch) FIELD(Metadata,source_stack_epoch) FIELD(Metadata,paint_call_serial) FIELD(Metadata,own_shadow_address_point) FIELD(Metadata,own_paint_callback) FIELD(Metadata,owner_present) FIELD(Metadata,geometry_present) FIELD(Metadata,paint_present) FIELD(Metadata,shadow_table_ready) FIELD(Metadata,source_anchor_startup) FIELD(Metadata,source_anchor_relation) FIELD(Metadata,mask_enabled) FIELD(Metadata,full_source_mapping_verified) FIELD(Metadata,fresh_blit_verified) FIELD(Metadata,surface_lease_verified) FIELD(Metadata,native_provider_getter_called) FIELD(Metadata,native_fill_called) FIELD(Metadata,native_ui_mutation_called) FIELD(Metadata,reserved) FIELD(Metadata,owner_before) FIELD(Metadata,owner_after) FIELD(Metadata,geometry_before) FIELD(Metadata,geometry_after) FIELD(Metadata,paint) END()}
 std::printf(",");{BEGIN(OwnerFacts) FIELD(OwnerFacts,owner) FIELD(OwnerFacts,actual_lv_vtable) FIELD(OwnerFacts,provider) FIELD(OwnerFacts,provider_vtable) FIELD(OwnerFacts,getter_target) FIELD(OwnerFacts,present_target) FIELD(OwnerFacts,configurator_provider) FIELD(OwnerFacts,resource_wrapper) FIELD(OwnerFacts,lv_resource_wrapper) FIELD(OwnerFacts,resource_provider) FIELD(OwnerFacts,resource_provider_vtable) FIELD(OwnerFacts,popup_header) FIELD(OwnerFacts,popup_root) FIELD(OwnerFacts,popup_selected) FIELD(OwnerFacts,provider_typeinfo) FIELD(OwnerFacts,provider_offset_to_top) FIELD(OwnerFacts,getter_first16) FIELD(OwnerFacts,present_first16) FIELD(OwnerFacts,provider_header_present) FIELD(OwnerFacts,getter_prefix_present) FIELD(OwnerFacts,present_prefix_present) FIELD(OwnerFacts,getter_in_original_user_executable_load) FIELD(OwnerFacts,provider_alias_equal) FIELD(OwnerFacts,resource_alias_equal) FIELD(OwnerFacts,popup_title) FIELD(OwnerFacts,popup_depth) FIELD(OwnerFacts,stack_shape) FIELD(OwnerFacts,shadow_instance) END()}
 std::printf(",");{BEGIN(GeometryFacts) FIELD(GeometryFacts,scalars) FIELD(GeometryFacts,access) FIELD(GeometryFacts,engine) FIELD(GeometryFacts,buffer) FIELD(GeometryFacts,config_point_candidates) FIELD(GeometryFacts,config_point_model_valid) FIELD(GeometryFacts,config_equals_slot) FIELD(GeometryFacts,config_equals_roi) FIELD(GeometryFacts,slot_equals_roi) END()}
 std::printf(",");{BEGIN(PaintFacts) FIELD(PaintFacts,thread_pointer) FIELD(PaintFacts,wrapper_frame) FIELD(PaintFacts,caller_pc) FIELD(PaintFacts,control_frame) FIELD(PaintFacts,manager_frame) FIELD(PaintFacts,lv) FIELD(PaintFacts,surface) FIELD(PaintFacts,draw_arg) FIELD(PaintFacts,clip_arg) FIELD(PaintFacts,draw_owner) FIELD(PaintFacts,draw_vtable) FIELD(PaintFacts,input_draw) FIELD(PaintFacts,input_clip) FIELD(PaintFacts,display_bounds) FIELD(PaintFacts,original_return) FIELD(PaintFacts,post_draw) FIELD(PaintFacts,post_clip) FIELD(PaintFacts,post_display_bounds) FIELD(PaintFacts,pitch_pixels) FIELD(PaintFacts,height) FIELD(PaintFacts,original_returned_normally) FIELD(PaintFacts,geometry_equal_before_after) FIELD(PaintFacts,post_pitch_pixels) FIELD(PaintFacts,post_height) FIELD(PaintFacts,surface_metadata_equal) FIELD(PaintFacts,reserved) END()}
 std::printf(",");{BEGIN(WireGeometry) FIELD(WireGeometry,local_control) FIELD(WireGeometry,recursive_bounds_candidate) FIELD(WireGeometry,locked_roi) FIELD(WireGeometry,pan_x) FIELD(WireGeometry,pan_y) FIELD(WireGeometry,scale) FIELD(WireGeometry,normal_fit_scale) FIELD(WireGeometry,rotation) FIELD(WireGeometry,client_id) FIELD(WireGeometry,access_owner) FIELD(WireGeometry,config_width) FIELD(WireGeometry,config_height) FIELD(WireGeometry,slot_width) FIELD(WireGeometry,slot_height) FIELD(WireGeometry,countdown) FIELD(WireGeometry,software_completion_id) FIELD(WireGeometry,locked_slot) FIELD(WireGeometry,parent_depth) FIELD(WireGeometry,alignment_flags) FIELD(WireGeometry,running) FIELD(WireGeometry,visible) FIELD(WireGeometry,pan_animation) FIELD(WireGeometry,borrowed_pointer_present) FIELD(WireGeometry,retain_borrowed) FIELD(WireGeometry,locked_metadata_present) FIELD(WireGeometry,recursive_bounds_candidate_present) FIELD(WireGeometry,parent_transform_would_update_local_size) FIELD(WireGeometry,consistent_double_read) FIELD(WireGeometry,reserved) END()}
 std::printf(",");{BEGIN(Owner) FIELD(Owner,queue) FIELD(Owner,manager) FIELD(Owner,data) FIELD(Owner,lv) FIELD(Owner,popup) END()}
 std::printf(",");{BEGIN(Rectangle24) FIELD(Rectangle24,address_point) FIELD(Rectangle24,x) FIELD(Rectangle24,y) FIELD(Rectangle24,width) FIELD(Rectangle24,height) END()}
 std::printf(",");{BEGIN(geometry03::Point8) FIELD(geometry03::Point8,x) FIELD(geometry03::Point8,y) END()}
 std::printf("}\n");
}
