#include "normal_fit.hpp"
#include "hook_capture.hpp"
#include "provider.hpp"
#include <cassert>
#include <cstdio>
#include <cstring>
#include <map>
#include <vector>
using namespace iq4::f1::normal08;
namespace iq4::f1::normal08 {struct OwnedFixture {static PaintToken token(const WriteFacts&w)noexcept{return PaintToken(w);}};}
namespace {
struct Host {
 std::map<Address,unsigned char>memory;
 iq4::f1::native_ui02::Owner owner{0x10000,0x20000,0x28000,0x30000,0x38000};
 Address thread{owner.queue};unsigned invalidates{},fills{};bool throw_fill{};
 std::vector<Rect>bands;
 static Host*active;
 template<class T>void put(Address a,const T&v){const auto*b=reinterpret_cast<const unsigned char*>(&v);for(std::size_t i=0;i<sizeof v;i++)memory[a+i]=b[i];}
 void zero(Address a,std::size_t n){for(std::size_t i=0;i<n;i++)memory[a+i]=0;}
 static bool read(void*p,Address a,void*out,std::size_t n)noexcept{auto&h=*static_cast<Host*>(p);for(std::size_t i=0;i<n;i++){auto q=h.memory.find(a+i);if(q==h.memory.end())return false;static_cast<unsigned char*>(out)[i]=q->second;}return true;}
 static Address current(void*p)noexcept{return static_cast<Host*>(p)->thread;}
 static void invalidate(void*,bool force){assert(!force);++active->invalidates;}
 static void fill(void*s,const iq4::f1::native_overlay::Rectangle24*d,const iq4::f1::native_overlay::Rectangle24*c,const iq4::f1::native_overlay::Color4*color){assert(reinterpret_cast<Address>(s)==0x40000&&d->address_point==0xb73b98&&c->address_point==0xb73b98&&color->alpha==166&&!color->c1&&!color->c2&&!color->c3);++active->fills;active->bands.push_back({d->x,d->y,d->width,d->height});if(active->throw_fill)throw 1;}
 Host(){active=this;zero(owner.queue,0x2000);zero(owner.manager,0x1000);zero(owner.lv,0x3000);zero(0x40000,0x38);zero(0x41000,8);
  put(owner.queue,Address{0xb91f48});put(owner.queue+0x1c8,owner.manager);put(owner.manager,Address{0xb8f358});put(owner.manager+8,owner.queue);put(owner.queue+0x9b8,owner.data);put(owner.manager+0x790,owner.data);put(owner.queue+0x8c0,owner.lv);put(owner.lv,Address{0xb9a9d8});put(owner.lv+0xb0,owner.manager);
  for(Address l:{owner.manager+0x40,owner.manager+0x68}){put(l,Address{0xb8f4e8});put(l+8,Address{0xc22908});put(l+16,Address{0xc22960});}
  const auto p=owner.manager+0x50,n=owner.manager+0x78,node=owner.lv+0x88;put(p+8,p);put(p+16,p);put(n+8,node);put(n+16,node);put(node,Address{0xb9abf8});put(node+8,n);put(node+16,n);put(node+24,owner.lv);
  put(0x40000,Address{0xb7b780});put(0x40008,Address{0x41000});put(0x40014,std::int32_t{1280});put(0x40018,std::int32_t{720});put(0x40020,iq4::f1::native_overlay::Rectangle24{0xb73b98,0,0,1280,720});put(0x41000,Address{0xb7b7d8});
 }
 iq4::f1::native_ui02::Memory mem(){return {this,read};}
 iq4::f1::native_ui02::Native native(){iq4::f1::native_ui02::Native n{};n.context=this;n.current_thread=current;n.invalidate=invalidate;return n;}
 WriteFacts facts(unsigned serial=1){WriteFacts w{};w.queue=owner.queue;w.lv=owner.lv;w.surface=0x40000;w.draw=0x41000;w.provider=0x42000;w.provider_vtable=0xb80000;w.getter_target=0x500000;w.manager_frame=0x43000;w.paint_serial=serial;w.geometry_epoch=1;auto&g=w.geometry;g.source_width=800;g.source_height=600;g.source_rectangle=g.clipped_source_rectangle={0,0,800,600};g.image_viewport={240,60,800,600};g.display_bounds=g.clip={0,0,1280,720};g.scale=g.normal_fit_scale=1;w.stock_clean_coverage=g.image_viewport;return w;}
 std::pair<ScalerCapture,ActualProviderContract>actual_fixture(){
  // Entirely owned simulated memory; no vendor image/call/target execution.
  ActualProviderContract p{};p.profile=ProviderProfile::RootReviewedInlineUIRetainedUntilPresent;p.getter_shape=InlineGetterShape::LeafAddRet8;std::memcpy(p.actual_UserSHA,iq4::f1::native_overlay::UserSHA,65);std::memset(p.owner_review_sha256,'a',64);std::memset(p.hook_quiescence_receipt_sha256,'b',64);p.owner=owner;p.provider=0x3ff00;p.provider_vtable=0x61000;p.getter=0x62000;p.present=0x63000;p.inline_surface_offset=0x100;p.near_entry=0x500000;p.near_trampoline=0x500100;p.own_bridge=0x7fff00004000;
  put(owner.manager+0x108,p.provider);put(p.provider,p.provider_vtable);put(p.provider_vtable+0x18,p.getter);put(p.provider_vtable+0x10,p.present);put(p.getter,std::uint32_t{0x91040000});put(p.getter+4,std::uint32_t{0xd65f03c0});put(0xb7b7f0,Address{0x47e9d0});
  auto b=[](Address from,Address to){return std::uint32_t(0x14000000|((std::int64_t(to)-std::int64_t(from))/4&0x3ffffff));};put(0x47f910,b(0x47f910,p.near_entry));put(p.near_trampoline,std::uint32_t{0xd10403ff});put(p.near_trampoline+4,b(p.near_trampoline+4,0x47f914));put(p.near_entry,std::uint32_t{0x58000050});put(p.near_entry+4,std::uint32_t{0xd61f0200});put(p.near_entry+8,p.own_bridge);
  for(Address f:{0x50000,0x51000,0x52000,0x53000,0x54000})zero(f,0x200);
  put(0x50000,Address{0x51000});put(0x50008,Address{0x47718c});put(0x51000,Address{0x52000});put(0x51008,Address{0x51ddd0});put(0x52000,Address{0x53000});put(0x52008,Address{0x4abe94});put(0x53000,Address{0x54000});put(0x53008,Address{0x4e33bc});
  put(0x52038,owner.lv);put(0x52030,Address{0x40000});put(0x53048,owner.lv);put(0x53040,Address{0x40000});put(0x54028,owner.manager);put(0x54148,Address{0x40000});put(0x54150,owner.lv);put(0x50058,Address{0x40000});put(0x50030,Address{0x57000});put(0x50038,Address{0x56000});put(0x50040,Address{0x55000});
  put(0x55000,iq4::f1::native_overlay::Rectangle24{0xb73b98,0,0,800,600});put(0x50068,iq4::f1::native_overlay::Rectangle24{0xb73b98,0,0,800,600});put(0x56000,iq4::f1::native_overlay::Rectangle24{0xb73b98,0,0,1280,720});put(0x57000,std::array<std::int32_t,4>{0,800,600,2400});
  put(0x50054,std::int32_t{240});put(0x50050,std::int32_t{60});put(0x5004c,float{1});put(owner.lv+0x190,float{1});put(owner.lv+0x194,float{1});put(owner.lv+0x104,std::uint8_t{1});put(owner.lv+0x6f,std::uint8_t{1});put(0x5a010,owner.queue);
  put(0x520a0,iq4::f1::native_overlay::Rectangle24{0xb73b98,0,0,800,600});put(0x520b8,std::array<std::int32_t,2>{800,600});put(owner.lv+0x108,Address{0x5b000});put(owner.data+0x118,Address{0x5b000});put(0x5b000,Address{0xc07da8});put(0x5b008,Address{0x5c000});put(0x60764,std::int32_t{800});put(0x60768,std::int32_t{600});
  ScalerCapture c{};c.original_fp=0x50000;c.original_lr=0x475908;c.thread_pointer=0x5a000;c.arguments[0]=0x41000;c.arguments[2]=0x58000;c.arguments[3]=2;c.arguments[4]=0x59000;c.arguments[6]=800;c.arguments[7]=600;c.stack_arguments[0]=2400;c.stack_arguments[1]=800;c.stack_arguments[2]=600;c.stack_arguments[3]=5120;return {c,p};
 }
};Host*Host::active{};
bool overlap(Rect a,Rect b){return a.x<b.x+b.width&&b.x<a.x+a.width&&a.y<b.y+b.height&&b.y<a.y+a.height;}
}
int main(){
 unsigned groups=0;
 {Host h;Renderer r;assert(r.bind_once_on_ui(h.mem(),h.native(),Host::fill,h.owner,nullptr));auto p=r.selection_port();assert(p.apply_on_ui(p.context,iq4::MaskMode::Ratio1_1,1)==iq4::f1::entry07::SelectResult::Rejected);assert(!h.fills&&!h.invalidates&&!r.status_on_ui().actual_geometry_known);assert(p.apply_on_ui(p.context,iq4::MaskMode::Off,1)==iq4::f1::entry07::SelectResult::AlreadyOff);++groups;}
 {Host h;Renderer r;assert(r.bind_once_on_ui(h.mem(),h.native(),Host::fill,h.owner,nullptr));assert(r.after_native_write_on_ui(OwnedFixture::token(h.facts())));unsigned serial=2,generation=1;
  for(auto mode:{iq4::MaskMode::XPan65_24,iq4::MaskMode::Ratio16_9,iq4::MaskMode::Ratio3_2,iq4::MaskMode::Ratio1_1}){auto p=r.selection_port();assert(p.apply_on_ui(p.context,mode,generation++)==iq4::f1::entry07::SelectResult::AwaitingStockPaint);h.bands.clear();assert(r.after_native_write_on_ui(OwnedFixture::token(h.facts(serial++))));assert(r.status_on_ui().phase==Phase::Shown&&!h.bands.empty());for(std::size_t i=0;i<h.bands.size();i++)for(std::size_t j=0;j<i;j++)assert(!overlap(h.bands[i],h.bands[j]));}
  assert(h.invalidates==4&&r.status_on_ui().actual_geometry_known);++groups;
  auto p=r.selection_port();const auto before=h.fills;assert(p.apply_on_ui(p.context,iq4::MaskMode::Off,generation++)==iq4::f1::entry07::SelectResult::AwaitingStockPaint);assert(!r.off_and_detach_on_ui(9));assert(r.after_native_write_on_ui(OwnedFixture::token(h.facts(serial++))));assert(h.fills==before&&r.status_on_ui().factory_restored);assert(r.off_and_detach_on_ui(10));++groups;
 }
 {Host h;Renderer r;assert(r.bind_once_on_ui(h.mem(),h.native(),Host::fill,h.owner,nullptr));assert(r.after_native_write_on_ui(OwnedFixture::token(h.facts())));auto p=r.selection_port();assert(p.apply_on_ui(p.context,iq4::MaskMode::Ratio16_9,1)==iq4::f1::entry07::SelectResult::AwaitingStockPaint);assert(r.after_native_write_on_ui(OwnedFixture::token(h.facts(2))));const auto n=h.fills;auto w=h.facts(3);w.geometry.pan.x=1;assert(r.after_native_write_on_ui(OwnedFixture::token(w)));assert(r.status_on_ui().phase==Phase::Hidden&&h.fills==n&&!r.status_on_ui().actual_geometry_known);assert(r.after_native_write_on_ui(OwnedFixture::token(h.facts(4))));assert(r.status_on_ui().phase==Phase::Shown&&h.fills>n);++groups;}
 {Host h;Renderer r;assert(r.bind_once_on_ui(h.mem(),h.native(),Host::fill,h.owner,nullptr));assert(r.after_native_write_on_ui(OwnedFixture::token(h.facts())));auto w=h.facts(2);w.geometry.clip={240,60,400,600};assert(!r.after_native_write_on_ui(OwnedFixture::token(w)));assert(!h.fills&&r.status_on_ui().last_paint==1);w=h.facts(2);w.geometry.image_viewport={0,0,400,300};assert(!r.after_native_write_on_ui(OwnedFixture::token(w)));assert(!h.fills);++groups;}
 {Host h;Renderer r;assert(r.bind_once_on_ui(h.mem(),h.native(),Host::fill,h.owner,nullptr));assert(r.after_native_write_on_ui(OwnedFixture::token(h.facts())));assert(!r.after_native_write_on_ui(OwnedFixture::token(h.facts())));h.thread=0;auto p=r.selection_port();assert(p.apply_on_ui(p.context,iq4::MaskMode::Ratio1_1,1)==iq4::f1::entry07::SelectResult::Rejected);h.thread=h.owner.queue;auto w=h.facts(2);w.draw+=8;assert(!r.after_native_write_on_ui(OwnedFixture::token(w)));assert(!h.fills);++groups;}
 {Host h;iq4::display::ViewMapping mapping{};auto g=h.facts().geometry;for(int rotation:{0,90,180,270}){g.rotation=rotation;assert(normal_mapping(g,mapping)==GeometryResult::NormalFullView);auto p=mapping.sourceToDisplay.map({0,0});assert(p.x>=240&&p.x<=1040&&p.y>=60&&p.y<=660);}g.scale=2;assert(normal_mapping(g,mapping)==GeometryResult::ZoomOrPan&&!mapping.fullSourceMappingKnown);g.scale=1;g.clipped_source_rectangle.width=799;assert(normal_mapping(g,mapping)==GeometryResult::PartialSource);g=h.facts().geometry;g.scale=0;assert(normal_mapping(g,mapping)==GeometryResult::Invalid);++groups;}
 {Host h;Renderer r;assert(r.bind_once_on_ui(h.mem(),h.native(),Host::fill,h.owner,nullptr));assert(r.after_native_write_on_ui(OwnedFixture::token(h.facts())));auto p=r.selection_port();assert(p.apply_on_ui(p.context,iq4::MaskMode::Ratio1_1,1)==iq4::f1::entry07::SelectResult::AwaitingStockPaint);h.throw_fill=true;assert(!r.after_native_write_on_ui(OwnedFixture::token(h.facts(2))));assert(r.status_on_ui().phase==Phase::Hold&&!r.off_and_detach_on_ui(10));++groups;}
 {Host h;Renderer r;assert(r.bind_once_on_ui(h.mem(),h.native(),Host::fill,h.owner,nullptr));auto a=h.actual_fixture();ProvenProviderAdapter observer;assert(observer.bind_observation_on_actual_ui(h.mem(),h.native(),h.owner));assert(observer.sample_boundary_scalars_on_actual_ui()==IngressResult::BoundaryObserved&&observer.status_on_ui().last.surface==0x40000&&!observer.status_on_ui().emitted&&!observer.status_on_ui().last.paint_serial&&!r.status_on_ui().actual_geometry_known&&!h.fills);assert(observer.observe_scaler_return_on_ui(a.first)==IngressResult::Observed&&!observer.status_on_ui().emitted&&!r.status_on_ui().actual_geometry_known&&!h.fills);ProvenProviderAdapter p;auto absent=a.second;absent.profile=ProviderProfile::Unknown;assert(!p.configure_on_actual_ui(h.mem(),h.native(),absent));assert(p.configure_on_actual_ui(h.mem(),h.native(),a.second));assert(p.dispatch_scaler_return_on_ui(a.first,r)==IngressResult::Emitted);auto port=r.selection_port();assert(port.apply_on_ui(port.context,iq4::MaskMode::Ratio1_1,1)==iq4::f1::entry07::SelectResult::AwaitingStockPaint);assert(p.dispatch_scaler_return_on_ui(a.first,r)==IngressResult::Emitted&&h.fills);auto bad=a.first;bad.stack_arguments[1]=0;assert(p.dispatch_scaler_return_on_ui(bad,r)==IngressResult::NoWrite);bad=a.first;bad.original_lr=0x475838;assert(p.dispatch_scaler_return_on_ui(bad,r)==IngressResult::UnsupportedCall);bad=a.first;bad.arguments[5]=2;assert(p.dispatch_scaler_return_on_ui(bad,r)==IngressResult::UnsupportedFormat);++groups;}
 {Host h;Renderer r;assert(r.bind_once_on_ui(h.mem(),h.native(),Host::fill,h.owner,nullptr));auto a=h.actual_fixture();ProvenProviderAdapter p;h.put(a.second.getter,std::uint32_t{0xf9400400});assert(!p.configure_on_actual_ui(h.mem(),h.native(),a.second));h.put(a.second.getter,std::uint32_t{0x91040000});assert(p.configure_on_actual_ui(h.mem(),h.native(),a.second));h.put(a.second.provider_vtable+0x18,Address{0x62008});assert(p.dispatch_scaler_return_on_ui(a.first,r)==IngressResult::UnknownLease);h.put(a.second.provider_vtable+0x18,a.second.getter);const std::uint32_t o0[6]={0xd10043ff,0xf90007e0,0xf94007e0,0x91040000,0x910043ff,0xd65f03c0};for(unsigned i=0;i<6;i++)h.put(a.second.getter+4*i,o0[i]);auto c=a.second;c.getter_shape=InlineGetterShape::OriginalO0StackAddRet24;ProvenProviderAdapter p2;assert(p2.configure_on_actual_ui(h.mem(),h.native(),c)&&p2.dispatch_scaler_return_on_ui(a.first,r)==IngressResult::Emitted);h.put(0x47f910,std::uint32_t{0xd10403ff});assert(p.dispatch_scaler_return_on_ui(a.first,r)==IngressResult::PatchMismatch);assert(!h.fills);++groups;}
 {Host h;Renderer r;assert(r.bind_once_on_ui(h.mem(),h.native(),Host::fill,h.owner,nullptr));assert(r.after_native_write_on_ui(OwnedFixture::token(h.facts())));auto p=r.selection_port();assert(p.apply_on_ui(p.context,iq4::MaskMode::Ratio1_1,1)==iq4::f1::entry07::SelectResult::AwaitingStockPaint);assert(r.after_native_write_on_ui(OwnedFixture::token(h.facts(2))));auto zoom=h.facts(3);zoom.geometry.pan.x=1;zoom.geometry.image_viewport=zoom.stock_clean_coverage={0,0,1280,720};const auto fills=h.fills;assert(r.after_native_write_on_ui(OwnedFixture::token(zoom))&&r.status_on_ui().phase==Phase::Hidden&&r.status_on_ui().factory_restored&&h.fills==fills);assert(r.after_native_write_on_ui(OwnedFixture::token(h.facts(4)))&&r.status_on_ui().phase==Phase::Shown&&h.fills>fills);++groups;}
 assert(groups==11);std::puts("11 owned normal-fit/production-ingress/OFF/zoom/owner fault groups PASS; target execution zero");
}
