#!/usr/bin/env python3
"""Read exact original bytes; generate only own local evidence/signatures."""
import hashlib,json,pathlib,struct,subprocess
ROOT=pathlib.Path(__file__).resolve().parents[3]
SRC=ROOT/'tools/firmware/f3_native_card_bridge_05'
OUT=ROOT/'analysis/firmware/f3_native_card_bridge_static_05'
ELF=ROOT/'analysis/firmware/extracted/P1Linux_6.03.21.bin'
SHA='9b611efe64067685b770ba3984ae951684c5a401f73f77a03b316be374032cdb'
WINDOWS={
 'Main_actual_SDWrite_XQDWrite_construction':(0x419028,0x419094),
 'Main_JPEG_actual_owner_arguments':(0x424b80,0x424bd4),
 'DeviceRequest_register_client':(0x8ca3ec,0x8ca4c4),
 'DeviceRequest_request':(0x8ca598,0x8ca708),
 'DeviceRequest_release':(0x8ca708,0x8ca888),
 'DeviceRequest_wait_request':(0x8ca888,0x8ca9f8),
 'AsynchronousDeviceRequest_wait':(0x8cafbc,0x8cb198),
 'DeviceRequest_ctor_global_list':(0x8ca264,0x8ca390),
 'AsynchronousDeviceRequest_constructor':(0x8cac94,0x8cae18),
 'AsynchronousDeviceRequest_request_release_get':(0x8cae94,0x8cafbc),
 'DeviceRequestProperty_set':(0x8cb94c,0x8cb9cc),
 'NativeFilesystem_root_setter':(0x8279c0,0x827aac),
 'NativeFilesystem_path_prefix':(0x827348,0x82744c),
 'Filesystem_factory_nongetter':(0x74e454,0x74e59c),
 'Main_SDInserted_SDHotplug_ctor':(0x4275a0,0x427610),
 'SD_presence_native_event_subscription':(0x46be10,0x46befc),
 'NativeFilesystem_open':(0x825ed4,0x82600c)}
TABLES={'AsynchronousDeviceRequest_vtable':(0xdb6628,72),'LinuxFilesystem_vtable':(0xd91450,304),'SD_FS_registry':(0xf55e18,32),'XQD_FS_registry':(0xf55e38,32)}
REQUIRED=['DeviceRequest_register_client','DeviceRequest_release','DeviceRequest_wait_request','AsynchronousDeviceRequest_wait','AsynchronousDeviceRequest_vtable','LinuxFilesystem_vtable']
def main():
 b=ELF.read_bytes();assert hashlib.sha256(b).hexdigest()==SHA
 ph=struct.unpack_from('<Q',b,32)[0];n=struct.unpack_from('<H',b,56)[0]
 loads=[struct.unpack_from('<IIQQQQQQ',b,ph+i*56) for i in range(n)]
 def raw(va,size):
  for t,f,o,v,p,fs,ms,a in loads:
   if t==1 and v<=va and va+size<=v+fs:return b[o+va-v:o+va-v+size]
  raise ValueError(hex(va))
 OUT.mkdir(parents=True,exist_ok=True);records=[];arrays=[]
 for name,(lo,hi) in WINDOWS.items():
  data=raw(lo,hi-lo);records.append({'name':name,'va':lo,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest(),'hex':data.hex()})
  dis=subprocess.run(['/Library/Developer/CommandLineTools/usr/bin/llvm-objdump','-d',f'--start-address={lo}',f'--stop-address={hi}',str(ELF)],capture_output=True,text=True,check=True).stdout
  (OUT/(name+'.asm')).write_text(dis)
 for name,(va,size) in TABLES.items():
  data=raw(va,size);records.append({'name':name,'va':va,'bytes':size,'sha256':hashlib.sha256(data).hexdigest(),'hex':data.hex()})
 for rec in records:
  if rec['name'] in REQUIRED:
   ident='sig_'+rec['name'];arrays.append(f'static const unsigned char {ident}[]={{'+','.join('0x'+rec['hex'][i:i+2] for i in range(0,len(rec['hex']),2))+'};')
 rows=[f'{{0x{r["va"]:x},sizeof(sig_{r["name"]}),sig_{r["name"]}}}' for r in records if r['name'] in REQUIRED]
 text='/* Exact fixed stock User, generated by collect_static.py. */\nstruct F3Signature05 {uintptr_t va;size_t size;const unsigned char*data;};\n'+'\n'.join(arrays)+'\nstatic const struct F3Signature05 f3_signatures05[]={'+','.join(rows)+'};\n'
 (SRC/'signatures.inc').write_text(text)
 (OUT/'EXACT.json').write_text(json.dumps({'schema':'iq4_f3_card_native_static_05','stock_user_sha256':SHA,'records':records,'runtime_observed':False},indent=2)+'\n')
 print(json.dumps({'windows':len(WINDOWS),'tables':len(TABLES),'target_executed':False}))
if __name__=='__main__':main()
