#include "../../src/recording/rgb_jpeg_backend.hpp"
#include "../../src/recording/mjpeg_avi.hpp"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <limits>
#include <stdexcept>

using namespace iq4;
namespace {
unsigned passed=0,failed=0;
void check(bool v,const char* text="check failed"){if(!v)throw std::runtime_error(text);}
void test(const char* n,const std::function<void()>& body){try{body();++passed;std::cout<<"PASS "<<n<<'\n';}catch(const std::exception& e){++failed;std::cerr<<"FAIL "<<n<<": "<<e.what()<<'\n';}}
Iq4JpegApi api(){return {jpeg_std_error,jpeg_CreateCompress,jpeg_set_defaults,jpeg_set_quality,jpeg_start_compress,jpeg_write_scanlines,jpeg_finish_compress,jpeg_destroy_compress,80,sizeof(jpeg_compress_struct),1};}
recording::RgbJpegOptions options(){return {96,64,96*3+17,(96*3+17)*64,90,100000};}
runtime::Frame rgb(unsigned index,std::int64_t pts){const auto o=options();runtime::Frame f;f.bytes.resize(o.maxInputBytes,0xdd);f.pts_ns=pts;f.source_sequence=40+index*2;for(unsigned y=0;y<o.height;++y)for(unsigned x=0;x<o.width;++x){const auto a=y*o.stride+x*3;f.bytes[a]=std::uint8_t((x*2+index*21)%256);f.bytes[a+1]=std::uint8_t((y*3+index*11)%256);f.bytes[a+2]=std::uint8_t((x+y+index)%2?40:220);}return f;}
struct SpyState{unsigned prepared=0,encoded=0,finalized=0,aborted=0;int fail=0;std::vector<runtime::Frame> received;};
struct Spy final:runtime::Backend{SpyState& s;explicit Spy(SpyState& state):s(state){}void prepare()override{++s.prepared;if(s.fail==1)throw std::runtime_error("injected prepare failure");}void encode(const runtime::Frame& f)override{++s.encoded;if(s.fail==2)throw std::runtime_error("injected downstream card failure");s.received.push_back(f);}void finalize()override{++s.finalized;if(s.fail==3)throw std::runtime_error("injected finalize failure");}void abort()noexcept override{++s.aborted;}};
void save(const std::filesystem::path& p,const std::vector<std::uint8_t>& bytes){std::ofstream f(p,std::ios::binary);f.write(reinterpret_cast<const char*>(bytes.data()),bytes.size());check(bool(f));}
std::vector<char> read(const std::filesystem::path& p){std::ifstream f(p,std::ios::binary);return {std::istreambuf_iterator<char>(f),std::istreambuf_iterator<char>()};}
void expected(const std::filesystem::path& folder,unsigned index,const runtime::Frame& frame){std::filesystem::create_directories(folder);const auto o=options();const Iq4JpegInput in{frame.bytes.data(),frame.bytes.size(),o.width,o.height,o.stride,o.quality};auto funcs=api();std::vector<std::uint8_t> packet(o.maxOutputBytes);Iq4JpegResult result{};check(iq4_jpeg_encode_bounded(&funcs,&in,packet.data(),packet.size(),&result)==IQ4_JPEG_OK);packet.resize(result.jpeg_bytes);save(folder/("packet_"+std::to_string(index+1)+".jpg"),packet);}
template<class F>void throws(F body){bool did=false;try{body();}catch(const std::exception&){did=true;}check(did,"expected exception");}
}
int main(int argc,char** argv){if(argc!=2)return 2;const std::filesystem::path out(argv[1]);std::filesystem::create_directories(out);
test("single allocation, immutable RGB, one packet and unchanged PTS/sequence",[&]{SpyState state;recording::RgbJpegBackend b(options(),api(),std::make_unique<Spy>(state));b.prepare();const auto capacity=b.packetBufferCapacity();auto frame=rgb(0,1234567890);const auto before=frame.bytes;b.encode(frame);check(frame.bytes==before&&state.encoded==1);check(state.received[0].pts_ns==frame.pts_ns&&state.received[0].source_sequence==frame.source_sequence);check(state.received[0].bytes.size()>100&&state.received[0].bytes[0]==0xff&&state.received[0].bytes[1]==0xd8);b.encode(rgb(1,1277000011));check(b.packetBufferCapacity()==capacity&&state.encoded==2);b.finalize();check(b.packetBufferCapacity()==0&&state.finalized==1);b.abort();b.abort();check(state.aborted==0);});
test("unverified table refuses before downstream IO",[&]{SpyState s;auto funcs=api();funcs.binding_abi_verified=0;recording::RgbJpegBackend b(options(),funcs,std::make_unique<Spy>(s));throws([&]{b.prepare();});check(s.prepared==0&&s.aborted==0&&b.packetBufferCapacity()==0);});
test("invalid explicit stride and input budget fail before allocation/card",[&]{for(unsigned c=0;c<3;++c){SpyState s;auto o=options();if(c==0)o.stride=1;if(c==1)o.stride=std::numeric_limits<std::size_t>::max();if(c==2)o.maxInputBytes=100;recording::RgbJpegBackend b(o,api(),std::make_unique<Spy>(s));throws([&]{b.prepare();});check(!s.prepared&&!s.aborted&&!b.packetBufferCapacity());}});
test("capacity failure aborts once, releases buffer and emits no packet",[&]{SpyState s;auto o=options();o.maxOutputBytes=16;recording::RgbJpegBackend b(o,api(),std::make_unique<Spy>(s));b.prepare();auto f=rgb(0,1);const auto before=f.bytes;throws([&]{b.encode(f);});check(b.lastCodecResult().status==IQ4_JPEG_OUTPUT_CAPACITY&&b.lastCodecResult().jpeg_bytes==0);check(s.encoded==0&&s.aborted==1&&f.bytes==before&&!b.packetBufferCapacity());b.abort();check(s.aborted==1);throws([&]{b.finalize();});});
test("truncated and oversized RGB do not reach the packet sink",[&]{for(bool tooLarge:{false,true}){SpyState s;recording::RgbJpegBackend b(options(),api(),std::make_unique<Spy>(s));b.prepare();auto f=rgb(0,1);f.bytes.resize(tooLarge?options().maxInputBytes+1:100);throws([&]{b.encode(f);});check(!s.encoded&&s.aborted==1&&!b.packetBufferCapacity());}});
test("prepare encode and finalize failures use idempotent downstream abort",[&]{for(int failure:{1,2,3}){SpyState s;s.fail=failure;auto b=std::make_unique<recording::RgbJpegBackend>(options(),api(),std::make_unique<Spy>(s));runtime::Recorder r(3,options().maxInputBytes,std::move(b));if(failure==1)check(!r.start());else{check(r.start());check(r.submit(rgb(0,1)));if(failure==2)check(!r.consume_one());else check(!r.stop());}check(r.state()==runtime::State::Error&&s.aborted==1);check(r.reset_error());check(s.aborted==1);}});
test("second prepare does not disturb the active session",[&]{SpyState s;recording::RgbJpegBackend b(options(),api(),std::make_unique<Spy>(s));b.prepare();throws([&]{b.prepare();});b.encode(rgb(0,1));b.finalize();check(s.prepared==1&&s.encoded==1&&s.finalized==1&&!s.aborted);b.prepare();b.abort();check(s.prepared==2&&s.aborted==1);});
const std::vector<std::int64_t> vfr{1000000000,1031000123,1077000456,1185123456,1249999999};
test("Owned RGB -> bounded JPEG -> Matroska preserves actual irregular source PTS",[&]{recording::MatroskaOptions o;o.directory=out.string();o.prefix="rgb_vfr";o.width=96;o.height=64;auto sink=std::make_unique<recording::MjpegMatroskaBackend>(o);auto* inspect=sink.get();auto adapter=std::make_unique<recording::RgbJpegBackend>(options(),api(),std::move(sink));runtime::Recorder r(2,options().maxInputBytes,std::move(adapter));check(r.start());for(unsigned i=0;i<vfr.size();++i){auto f=rgb(i,vfr[i]);expected(out/"expected_rgb_vfr",i,f);check(r.submit(std::move(f)));check(r.consume_one());}check(r.stop()&&r.counters().encoded==vfr.size());check(inspect->publication()==recording::Publication::Complete&&std::filesystem::exists(out/inspect->finalLeaf()));});
test("Owned RGB -> bounded JPEG -> strict CFR AVI retains supplied PTS journal",[&]{recording::AviOptions o;o.directory=out.string();o.prefix="rgb_cfr";o.width=96;o.height=64;o.rateNumerator=25;auto sink=std::make_unique<recording::MjpegAviBackend>(o);auto adapter=std::make_unique<recording::RgbJpegBackend>(options(),api(),std::move(sink));runtime::Recorder r(2,options().maxInputBytes,std::move(adapter));check(r.start());for(unsigned i=0;i<4;++i){auto f=rgb(i,2000000000+std::int64_t(i)*40000000);expected(out/"expected_rgb_cfr",i,f);check(r.submit(std::move(f)));check(r.consume_one());}check(r.stop()&&r.counters().encoded==4);});
test("source loss drains owned RGB then publishes completed VFR container",[&]{recording::MatroskaOptions o;o.directory=out.string();o.prefix="rgb_source_lost";o.width=96;o.height=64;auto sink=std::make_unique<recording::MjpegMatroskaBackend>(o);auto adapter=std::make_unique<recording::RgbJpegBackend>(options(),api(),std::move(sink));runtime::Recorder r(3,options().maxInputBytes,std::move(adapter));check(r.start());for(unsigned i=0;i<2;++i){auto f=rgb(i,vfr[i]);expected(out/"expected_rgb_source_lost",i,f);check(r.submit(std::move(f)));}r.source_lost();check(r.state()==runtime::State::Error&&r.counters().encoded==2);check(std::filesystem::exists(out/"rgb_source_lost_1.mkv"));check(r.reset_error());});
test("host container retains partial on codec capacity error",[&]{recording::MatroskaOptions o;o.directory=out.string();o.prefix="rgb_capacity_error";o.width=96;o.height=64;auto sink=std::make_unique<recording::MjpegMatroskaBackend>(o);auto config=options();config.maxOutputBytes=16;auto adapter=std::make_unique<recording::RgbJpegBackend>(config,api(),std::move(sink));runtime::Recorder r(1,config.maxInputBytes,std::move(adapter));check(r.start()&&r.submit(rgb(0,1))&&!r.consume_one());check(r.state()==runtime::State::Error&&!r.counters().encoded);check(!std::filesystem::exists(out/"rgb_capacity_error_1.mkv")&&std::filesystem::exists(out/"rgb_capacity_error_1.mkv.iq4rec.partial"));check(r.reset_error());});
test("RGB truncation abort preserves earlier packet for read-only partial recovery",[&]{recording::MatroskaOptions o;o.directory=out.string();o.prefix="rgb_truncated";o.width=96;o.height=64;auto sink=std::make_unique<recording::MjpegMatroskaBackend>(o);auto adapter=std::make_unique<recording::RgbJpegBackend>(options(),api(),std::move(sink));runtime::Recorder r(1,options().maxInputBytes,std::move(adapter));check(r.start());auto good=rgb(0,vfr[0]);expected(out/"expected_rgb_truncated",0,good);check(r.submit(std::move(good))&&r.consume_one());auto bad=rgb(1,vfr[1]);bad.bytes.resize(100);check(r.submit(std::move(bad))&&!r.consume_one());check(r.state()==runtime::State::Error&&r.counters().encoded==1);const std::string partial="rgb_truncated_1.mkv.iq4rec.partial";const auto before=read(out/partial);o.prefix="rgb_truncated_recovered";std::string final;check(recording::recoverMatroskaPartial(partial,o,final)==1);check(read(out/partial)==before&&std::filesystem::exists(out/final));});
test("irregular RGB PTS cannot be silently retimed by CFR downstream",[&]{recording::AviOptions o;o.directory=out.string();o.prefix="rgb_cfr_rejected";o.width=96;o.height=64;o.rateNumerator=25;auto sink=std::make_unique<recording::MjpegAviBackend>(o);auto adapter=std::make_unique<recording::RgbJpegBackend>(options(),api(),std::move(sink));runtime::Recorder r(1,options().maxInputBytes,std::move(adapter));check(r.start());auto good=rgb(0,vfr[0]);expected(out/"expected_rgb_cfr_rejected",0,good);check(r.submit(std::move(good))&&r.consume_one());check(r.submit(rgb(1,vfr[1]))&&!r.consume_one());check(r.state()==runtime::State::Error&&r.counters().encoded==1);const std::string partial="rgb_cfr_rejected_1.avi.iq4rec.partial";const auto before=read(out/partial);o.prefix="rgb_cfr_rejected_recovered";std::string final;check(recording::recoverPartial(partial,o,final)==1);check(read(out/partial)==before);});
std::cout<<"RESULT_JSON {\"evidence_level\":\"host_validation\",\"camera_binding\":false,\"hardware_fps_claimed\":false,\"passed\":"<<passed<<",\"failed\":"<<failed<<"}\n";return failed?1:0;
}
